8888CREATE DATABASE DevFlix;

USE DevFlix;

CREATE TABLE usuarios (
	id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	foto_perfil VARCHAR(100),
	nome_usuario VARCHAR(16) NOT NULL,
	data_nascimento DATE NOT NULL,
	email VARCHAR(100) NOT NULL,
	senha VARCHAR(8) NOT NULL,
	descricao TEXT,
	sexo VARCHAR(10) NOT NULL,
	nicho VARCHAR(16) NOT NULL,
	seguidores INT(11) DEFAULT 0,
	seguindo INT(11) DEFAULT 0,
	create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    update_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='Usuários que acessarão a base de dados';

CREATE TABLE podcasts(
	id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	id_usuario INT(11) NOT NULL,
	podcast VARCHAR(100) NOT NULL,
	genero VARCHAR(60) NOT NULL,
	nome_podcast VARCHAR(100) NOT NULL,
	imagem_podcast VARCHAR(100),
	acessos INT(11) DEFAULT 0,
	likes INT(11) DEFAULT 0,
	create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    update_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT FK_idUsuario_podcast FOREIGN KEY (id_usuario) REFERENCES usuarios (id)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='na base de dados';

CREATE TABLE playlist_podcasts(
	id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	id_podcast INT(11) NOT NULL,
	id_usuario INT(11) NOT NULL,
	musica VARCHAR(100) NOT NULL,
	nome_musica VARCHAR(60) NOT NULL,
	create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    update_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT fk_idPodcast_playlistPodcast FOREIGN KEY (id_podcast) REFERENCES podcasts (id),
    CONSTRAINT fk_idUsuario_playlistPodcast FOREIGN KEY (id_usuario) REFERENCES usuarios (id)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='Playlist criada pelos usuários';

CREATE TABLE favoritos(
	id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	id_playlist INT(11) NOT NULL,
	id_usuario INT(11) NOT NULL,
	nome_playlist VARCHAR(60) NOT NULL,
	genero VARCHAR(60) NOT NULL,
	imagem_playlist VARCHAR(100),
	create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    update_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

	CONSTRAINT fk_idPlaylist_favoritos FOREIGN KEY (id_playlist) REFERENCES playlist_podcasts (id),
    CONSTRAINT fk_idUsuario_favoritos FOREIGN KEY (id_usuario) REFERENCES usuarios (id)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='Barra podcasts demarcados como faritos pelo usuário';